# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/need-/Desktop/Shooter Game/Shooter Game.srcs/sources_1/ip/clk_divider/clk_divider.xci
# IP: The module: 'clk_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/need-/Desktop/Shooter Game/Shooter Game.srcs/sources_1/ip/clk_divider/clk_divider_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/need-/Desktop/Shooter Game/Shooter Game.srcs/sources_1/ip/clk_divider/clk_divider.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/need-/Desktop/Shooter Game/Shooter Game.srcs/sources_1/ip/clk_divider/clk_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/need-/Desktop/Shooter Game/Shooter Game.srcs/sources_1/ip/clk_divider/clk_divider.xci
# IP: The module: 'clk_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/need-/Desktop/Shooter Game/Shooter Game.srcs/sources_1/ip/clk_divider/clk_divider_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/need-/Desktop/Shooter Game/Shooter Game.srcs/sources_1/ip/clk_divider/clk_divider.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/need-/Desktop/Shooter Game/Shooter Game.srcs/sources_1/ip/clk_divider/clk_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
